# Generated by Django 3.1.5 on 2021-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(max_length=90, unique=True)),
                ('logo_home', models.ImageField(upload_to='', verbose_name='Your Logo')),
                ('profession', models.CharField(max_length=50)),
                ('who_i_am', models.CharField(max_length=1000, verbose_name='Tell something short about you')),
                ('text_for_backend', models.CharField(max_length=300, verbose_name='backend phrase')),
                ('text_for_front_end', models.CharField(max_length=300, verbose_name='frontend phrase')),
                ('text_for_appsdesktop', models.CharField(max_length=300, unique=True, verbose_name='apps phrase')),
            ],
        ),
        migrations.CreateModel(
            name='my_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_photo1', models.ImageField(upload_to='')),
                ('work_text1', models.CharField(max_length=400)),
                ('work_photo2', models.ImageField(upload_to='')),
                ('work_text2', models.CharField(max_length=400)),
                ('work_photo3', models.ImageField(upload_to='')),
                ('work_text3', models.CharField(max_length=400)),
                ('work_photo4', models.ImageField(upload_to='')),
                ('work_text4', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='')),
                ('text1', models.TextField()),
                ('photo2', models.ImageField(upload_to='')),
                ('text2', models.TextField()),
                ('hoto3', models.ImageField(upload_to='')),
                ('text3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(help_text='Please use your url facebook user page', verbose_name='Facebook URL User')),
                ('twitter', models.URLField(help_text='Please use your url twitter user page', verbose_name='Twtter Url User')),
                ('instagram', models.URLField(help_text='Please use your url Instagram user page', verbose_name='Instagram Url User')),
            ],
        ),
    ]
