# Generated by Django 3.1.5 on 2021-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='text_for_appsdesktop',
            field=models.CharField(default='python', max_length=300, unique=True, verbose_name='apps phrase'),
        ),
    ]
